[build-emacs-from-ftp] Prevent clean() from removing the whole directory when the above regular expression fails. Grrrrr.

diff --git a/build-emacs-from-ftp b/build-emacs-from-ftp
--- a/build-emacs-from-ftp
+++ b/build-emacs-from-ftp
@@ -9,6 +9,12 @@ LABEL=$([ x$2 = x ] || echo "$2-")
 
 eval `curl -s "$FTP_DIR_URL/" | perl -MSort::Versions -ne 'push @v, { s=>$1, d=>$2, p=>$3, v=>$4 } if /(\d+) (\w+ \d+ (?: \d+|\d+:\d+)) (emacs-([\d.]+).tar.gz)/; END { %r = %{${[sort { versioncmp $b->{v}, $a->{v} } @v]}[0]}; print "SIZE=$r{s}\nLATEST=$r{p}\nVERSION=$r{v}\nDATE=\"$r{d}\"\n" }'`
 
+# Prevent clean() from removing the whole directory when the above regular expression fails. Grrrrr.
+if [ x$LATEST = x ]; then
+	echo "Error retrieving latest version number from $FTP_DIR_URL." 1>&2
+	exit
+fi
+
 mkdir -p ftp-versions
 
 if [ \! -f ftp-versions/$LATEST ]; then
